### ISSUE TITLE
Esolang wiki

### ISSUE THREAD

**Issue by oerjan** [fuzzybow/fuzzybolge#1]
Hi, I'm an admin on the esolang wiki. I noticed you (given your username and this new repository, I assume it was you) got caught by our emergency spam filter in the middle of a spammer attack. Sorry about that.

I have opened up the wiki again, for now, although we may have to close it again (we haven't quite decided on a better way of handling the latest devious spammers yet.)

**Comment by fuzzybow** [comment]
Thanks! Yeah, there are several errors on the Malbolge page  I was looking to fix
